Alabama = ["west", "crimson", "white", True, "alabama"]
Arkansas= ["west", "red", "white", True, "arkansas"]
Auburn = ["west", "orange", "blue", True, "auburn"]
MississippiSt = ["west", "maroon", "white", True, "mississippi"]
LSU = ["west", "purple", "gold", True, "louisiana"]
TexasAM = ["west", "maroon", "white", True, "texas"]
OleMiss = ["west", "red","blue",True, "mississippi"]

Florida = ["east", "orange","blue", True, "florida"]
Georgia = ["east", "red","black", True,"georgia"]
Kentucky = ["east", "blue","white", True, "kentucky"]
OleMiss = ["west", "red","blue",True, "mississippi"]
Missouri = ["east", "black", "gold", True, "missouri"]
SouthCarolina =["east", "red", "black", True, "south carolina"]
Tennessee = ["east", "orange", "white", True, "tennessee"]
Vanderbilt = ["east", "black", "gold", False, "tennessee"]
